import { FileTreeItemType } from "@/interfaces/FileTreeItemType";

export interface InstructionType {
  label: string;
  context: { label: string; value: string }[];
  inputs: { label: string; value: string }[];
  outputs: { label: string; value: string }[];
  code: string;
}

export interface ProjectFileType {
  lib: string;
  mod: string;
  state: string;
}

export type ProjectStateUpdater =
  | ProjectStateType
  | ((prevState: ProjectStateType) => ProjectStateType);

export interface ProjectStateType {
  built?: boolean
  deployed?: boolean
  /** Public key of the deployed on-chain program (base-58). */
  programId?: string
  /** Anchor IDL (interface description language) for the program */
  idl?: any
  /** optional list of all IDLs we've received for this project */
  idls?: any[]

  /** Workflow graph — list of nodes generated by the canvas */
  nodes?: any[]

  /** Workflow graph — list of edges connecting nodes */
  edges?: any[]

  /** Instructions added to the workflow */
  instructions?: InstructionType[]

  /** Project files (lib, mod, state) */
  projectFiles?: ProjectFileType

  /** Arbitrary config object for the workflow / build */
  config?: Record<string, unknown>
}

// ---------------------------------------------------------------------------
//  JSON blob stored in `details`
//    • keep `projectState` for build/deploy flags
//    • add optional top-level `programId` so the deterministic public key
//      can live outside the nested object and survive merges
// ---------------------------------------------------------------------------
export interface ProjectDetailsType {
  /** Sub-object managed by the build/deploy pipeline */
  projectState?: Partial<ProjectStateType>

  /** Public program ID written by the build/deploy pipeline */
  programId?: string

  /** Function to update the project state */
  setProjectState?: (updater: ProjectStateUpdater) => void

  /** Allow future keys without another type bump */
  [key: string]: unknown
}

export interface ProjectContextType {
  id?: string;
  name?: string;
  description?: string;
  containerUrl?: string;
  details?: ProjectDetailsType;
  injectingNodeTypes?: string[];
}

// ----------- Save Project -----------
// ---------------------------------------------------------------------------
//  Payload used by `projectApi.updateProject`
// ---------------------------------------------------------------------------
export interface ProjectContextToSave {
  name?: string
  description?: string
  /** Free-form JSON persisted server-side */
  details?: ProjectDetailsType
}

export interface SaveProjectResponse {
  message: string;
  project: {
    id: string;
    name: string;
    description: string;
    org_id: string;
    root_path: string;
    details: any;
    last_updated: string;
    created_at: string;
  };
  directoryTask?: {
    taskId: string;
    message: string;
  };
  directoryTaskError?: string;
}

export interface ProjectListItem {
  id: string;
  name: string;
  description: string;
  created_at: string;
  last_updated: string;
  root_path: string;
}

export interface ListProjectsResponse {
  data: ProjectListItem[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

// Commenting out the savedKeys array as it references properties that no longer exist in ProjectStateType
/*
export const savedKeys: (keyof ProjectStateType)[] = [
    'nodes',
    'edges',
    'config',
    'programId',
    'instructions',
    'projectFiles',
    'fileTree',
    'built',
    'deployed',
    'idl',
    'idls',
];
*/