import type { Metadata } from 'next'
import '../src/globals.css'
import WalletConnectionProvider from '../src/context/WalletConnectionProvider';
import React from 'react';

export const metadata: Metadata = {
  title: 'SolanaFlow Token Minter',
  description: 'Generated by SolanaFlow',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <WalletConnectionProvider>
          {children}
        </WalletConnectionProvider>
      </body>
    </html>
  )
} 