"use client";

import "../src/globals.css";
import WalletConnectionProvider from "../src/context/WalletConnectionProvider";
import React from 'react';
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'SolanaFlow Token Minter',
  description: 'Generated by SolanaFlow',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="light" suppressHydrationWarning>
      <body className="min-h-screen bg-background font-sans antialiased">
        <WalletConnectionProvider>{children}</WalletConnectionProvider>
      </body>
    </html>
  )
} 