import "@solana/wallet-adapter-react-ui/styles.css";
import "./globals.css";
import React from 'react';
import type { Metadata } from 'next';
import ClientWalletProvider from "../src/components/WalletProvider";

export const metadata: Metadata = {
  title: 'SolanaFlow Token Minter',
  description: 'Generated by SolanaFlow',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="light" suppressHydrationWarning>
      <body className="min-h-screen bg-background font-sans antialiased">
        <ClientWalletProvider>{children}</ClientWalletProvider>
      </body>
    </html>
  )
} 