/**
 * Component Map for Dynamic Loading
 * This file is auto-generated by the build process
 * Maps component names to their import functions
 */

export const componentMap: Record<string, () => Promise<any>> = {
  // Components will be added here by code generation
  // Example: 'MyProgramApp': () => import('./generated/MyProgramApp'),
  
  // Default fallback component
  'FallbackApp': () => import('./defaults/FallbackApp'),
};

export default componentMap;