"use client"

import { useState, useEffect, useMemo } from "react"
import { WalletMultiButton } from "@solana/wallet-adapter-react-ui"
import { useWallet } from "@solana/wallet-adapter-react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip"
import { Badge } from "@/components/ui/badge"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { useToast } from "@/hooks/use-toast"
import { Copy, ExternalLink, Info, Moon, Sun, Loader2 } from "lucide-react"
import { useTheme } from "next-themes"
import * as anchor from "@coral-xyz/anchor"
import { PublicKey, Keypair, Transaction } from "@solana/web3.js"
// Local fallback IDL – generated by Anchor, bundled by the build pipeline
import solMintIdl from "../idl/solmint.json"
import { TOKEN_PROGRAM_ID, getAssociatedTokenAddress, createAssociatedTokenAccountInstruction } from "@solana/spl-token"
import {
  PROGRAM_ID as METADATA_PROGRAM_ID,
  createCreateMetadataAccountV3Instruction
} from "@metaplex-foundation/mpl-token-metadata"

/* ───────────────────────────
 *  Mini debug helper
 *    – console.groupCollapsed with ts-safe ellipsis
 *    – timestamps every call (Date.toISOString)
 * ─────────────────────────── */
function dbg(label: string, ...args: any[]) {
  const ts = new Date().toISOString()
  // Narrow stacks collapse nicely inside DevTools
  /* eslint-disable no-console */
  console.groupCollapsed(`[SolMintApp ${ts}] ${label}`)
  args.forEach(a => console.log(a))
  console.groupEnd()
  /* eslint-enable  no-console */
}

// Define extended IDL type with required address property
type AnchorIdl = anchor.Idl & { 
  address?: string;
  metadata?: { 
    address?: string;
    [key: string]: any;
  };
};

const { BN } = anchor

/* -------------------------------------------------------------------- *
 *  Generic helper: fetch IDL (fallback to bundled) and ensure
 *  `metadata.address` is present so Anchor ≥0.31 doesn't choke.
 * -------------------------------------------------------------------- */
async function getProgram(
  provider: anchor.AnchorProvider,
  programId: PublicKey,
): Promise<anchor.Program> {
  let idl = await anchor.Program.fetchIdl(programId, provider)
  if (!idl) {
    console.warn("[IDL] On-chain IDL missing – using bundled JSON")
    idl = solMintIdl as unknown as anchor.Idl
  }
  if (!(idl as any).metadata?.address) {
    idl = {
      ...(idl as any),
      metadata: { ...((idl as any).metadata ?? {}), address: programId.toBase58() },
    } as anchor.Idl
  }
  return new anchor.Program(idl as AnchorIdl, provider)
}

/* -------------------------------------------------------------------- *
 * Resolve Program ID – **env file only**.  The value is injected by the
 * build-pipeline into web/.env and we never touch it again at runtime.
 * -------------------------------------------------------------------- */
// Build-time value injected by the pipeline; no silent fall-back.
const INITIAL_PROGRAM_ID = process.env.NEXT_PUBLIC_PROGRAM_ID ?? "";

// Helper function needs to be defined before components that use it
const shortenAddress = (address: string) =>
  address && address.length > 8
    ? `${address.slice(0, 4)}...${address.slice(-4)}`
    : address;

// Debug Panel Component
const DebugPanel = ({ 
  programId, 
  programStatus, 
  walletPubKey, 
  mintPubKey,
  connection 
}: {
  programId: string
  programStatus: any
  walletPubKey: string | null
  mintPubKey: PublicKey | null
  connection: anchor.web3.Connection
}) => {
  const [expanded, setExpanded] = useState(false)
  const [balance, setBalance] = useState<number | null>(null)
  
  useEffect(() => {
    if (walletPubKey && expanded) {
      const checkBalance = async () => {
        try {
          const pubkey = new PublicKey(walletPubKey)
          const bal = await connection.getBalance(pubkey)
          setBalance(bal / anchor.web3.LAMPORTS_PER_SOL)
        } catch (error) {
          console.error('Failed to get balance:', error)
        }
      }
      checkBalance()
    }
  }, [walletPubKey, expanded, connection])
  
  return (
    <Card className="fixed bottom-4 right-4 z-50 max-w-md shadow-lg">
      <CardHeader 
        className="cursor-pointer pb-2"
        onClick={() => setExpanded(!expanded)}
      >
        <CardTitle className="text-sm flex items-center justify-between">
          Debug Info
          <Button variant="ghost" size="sm" className="h-6 w-6 p-0">
            {expanded ? "−" : "+"}
          </Button>
        </CardTitle>
      </CardHeader>
      {expanded && (
        <CardContent className="text-xs font-mono space-y-2">
          <div className="space-y-1">
            <div>Program ID: {programId || "Not set"}</div>
            <div>Wallet: {walletPubKey ? shortenAddress(walletPubKey) : "Not connected"}</div>
            {balance !== null && <div>Balance: {balance.toFixed(4)} SOL</div>}
            <div>RPC: {connection.rpcEndpoint}</div>
            <div>Mint: {mintPubKey?.toBase58() ? shortenAddress(mintPubKey.toBase58()) : "Not created"}</div>
          </div>
          {programStatus.deployed && (
            <div className="border-t pt-2 space-y-1">
              <div className="flex items-center gap-2">
                <span>Deployed:</span>
                <span className="text-green-600">✓</span>
              </div>
              <div className="flex items-center gap-2">
                <span>Executable:</span>
                <span className={programStatus.executable ? "text-green-600" : "text-red-600"}>
                  {programStatus.executable ? "✓" : "✗"}
                </span>
              </div>
              <div className="flex items-center gap-2">
                <span>Has IDL:</span>
                <span className={programStatus.hasIdl ? "text-green-600" : "text-yellow-600"}>
                  {programStatus.hasIdl ? "✓" : "Using fallback"}
                </span>
              </div>
              {programStatus.owner && (
                <div>Owner: {shortenAddress(programStatus.owner)}</div>
              )}
            </div>
          )}
        </CardContent>
      )}
    </Card>
  )
}

export default function SolMintApp() {
  const { publicKey, connected, signTransaction, signAllTransactions } = useWallet()
  const { theme, setTheme } = useTheme()
  const { toast } = useToast()
  
  const [programId, setProgramId] = useState(INITIAL_PROGRAM_ID)

  /* Dynamic connection based on URL params or environment */
  const connection = useMemo(() => {
    // Check URL params for cluster info
    const urlParams = new URLSearchParams(window.location.search);
    const cluster = urlParams.get('cluster');
    const rpcUrl = urlParams.get('rpcUrl');
    
    // Determine endpoint
    let endpoint = anchor.web3.clusterApiUrl("devnet"); // default
    
    if (cluster === 'local' && rpcUrl) {
      // Use proxy to avoid CORS issues when in iframe
      // The proxy in next.config.js forwards /rpc to localhost:28899
      const basePath = window.location.pathname.split('/').slice(0, 3).join('/');
      // IMPORTANT: Must use absolute URL with protocol for Connection constructor
      endpoint = `${window.location.origin}${basePath}/rpc`;
      console.log('[SolMint] Connecting to local validator via proxy:', endpoint);
    } else if (cluster === 'local') {
      // Fallback to proxy path
      const basePath = window.location.pathname.split('/').slice(0, 3).join('/');
      // IMPORTANT: Must use absolute URL with protocol for Connection constructor
      endpoint = `${window.location.origin}${basePath}/rpc`;
      console.log('[SolMint] Connecting to local validator via proxy (fallback):', endpoint);
    } else if (cluster && ['devnet', 'testnet', 'mainnet-beta'].includes(cluster)) {
      endpoint = anchor.web3.clusterApiUrl(cluster as any);
      console.log(`[SolMint] Connecting to ${cluster}:`, endpoint);
    }
    
    return new anchor.web3.Connection(endpoint, "confirmed");
  }, [])

  // Read program ID and cluster from URL params
  useEffect(() => {
    if (typeof window === 'undefined') return;
    
    const urlParams = new URLSearchParams(window.location.search);
    const urlProgramId = urlParams.get('programId');
    const cluster = urlParams.get('cluster');
    
    if (urlProgramId && urlProgramId !== programId) {
      setProgramId(urlProgramId);
      localStorage.setItem('programId', urlProgramId);
      console.log('[SolMint] Program ID from URL:', urlProgramId);
    }
    
    // Store cluster info for connection
    if (cluster) {
      localStorage.setItem('cluster', cluster);
    }
  }, []);

  // Update program ID if the parent window sends a PROGRAM_ID message or if the
  // value in localStorage changes.  This helps keep the iframe in sync with the
  // build pipeline which may update the .env file after the page has loaded.
  useEffect(() => {
    if (typeof window === 'undefined') return
    
    const handleMsg = (e: MessageEvent) => {
      if (e.data?.type === 'PROGRAM_ID' && typeof e.data.programId === 'string') {
        const id = e.data.programId
        if (id && id !== programId) {
          setProgramId(id)
          localStorage.setItem('programId', id)
        }
      }
    }
    
    const handleStorage = (e: StorageEvent) => {
      if (e.key === 'programId' && e.newValue && e.newValue !== programId) {
        setProgramId(e.newValue)
      }
    }

    window.addEventListener('message', handleMsg)
    window.addEventListener('storage', handleStorage)
    return () => {
      window.removeEventListener('message', handleMsg)
      window.removeEventListener('storage', handleStorage)
    }
  }, [programId])

  /* ---------- runtime helpers ---------- */
  const isBrowser    = typeof window !== "undefined";
  const isStandalone = isBrowser && window.parent === window;   // running top‑level, *not* inside iframe
  
  // Verify program deployment status
  useEffect(() => {
    if (!programId || programId.length < 32) return
    
    const verifyProgram = async () => {
      setProgramStatus(prev => ({ ...prev, checking: true }))
      
      try {
        const pubkey = new PublicKey(programId)
        
        // Check if program account exists
        const accountInfo = await connection.getAccountInfo(pubkey)
        
        if (accountInfo) {
          setProgramStatus(prev => ({
            ...prev,
            deployed: true,
            executable: accountInfo.executable,
            owner: accountInfo.owner.toBase58(),
            checking: false
          }))
          
          // Try to fetch IDL
          try {
            const fetchedIdl = await anchor.Program.fetchIdl(pubkey, { connection })
            setProgramStatus(prev => ({ ...prev, hasIdl: !!fetchedIdl }))
            if (fetchedIdl) {
              setIdl(fetchedIdl)
            }
          } catch {
            console.log('[VERIFY] No on-chain IDL found, will use bundled fallback')
            // Use fallback IDL if available
            setIdl(null)
          }
        } else {
          setProgramStatus(prev => ({
            ...prev,
            deployed: false,
            checking: false
          }))
        }
      } catch (error) {
        console.error('[VERIFY] Program verification failed:', error)
        setProgramStatus(prev => ({ ...prev, checking: false }))
      }
    }
    
    verifyProgram()
    // Re-verify every 10 seconds
    const interval = setInterval(verifyProgram, 10000)
    return () => clearInterval(interval)
  }, [programId, connection])
  
  // Fetch wallet balance
  useEffect(() => {
    if (!publicKey || !connection) return
    
    const fetchBalance = async () => {
      try {
        const balance = await connection.getBalance(publicKey)
        setWalletBalance(balance / anchor.web3.LAMPORTS_PER_SOL)
      } catch (error) {
        console.error('[BALANCE] Failed to fetch balance:', error)
        setWalletBalance(null)
      }
    }
    
    fetchBalance()
    // Refresh balance every 5 seconds
    const interval = setInterval(fetchBalance, 5000)
    return () => clearInterval(interval)
  }, [publicKey, connection])

  /* ───────── wallet info coming from the parent window ───────── */
  const [parentWallet, setParentWallet] =
    useState<{ connected: boolean; publicKey: string | null }>({
      connected: false,
      publicKey: null
    });

  useEffect(() => {
    if (!isBrowser) return;                       // guard during SSR
    function handleParentMsg(event: MessageEvent) {
      const { type, publicKey: pk } = event.data || {};
      if (type === "WALLET_CONNECTED" && pk) {
        setParentWallet({ connected: true, publicKey: pk });
        /* auto‑prefill mint authority if user didn't type anything */
        setInitMintForm(prev =>
          prev.mintAuthority ? prev : { ...prev, mintAuthority: pk }
        );
      }
    }
    window.addEventListener("message", handleParentMsg);
    return () => window.removeEventListener("message", handleParentMsg);
  }, [isBrowser, isStandalone]);

  /* helper flags that work with either in‑iframe extension _or_ parent bridge */
  const walletReady = connected || parentWallet.connected;
  const walletPubKey = connected && publicKey ? publicKey.toString() : parentWallet.publicKey;

  // Form states
  const [initMintForm, setInitMintForm] = useState({
    decimals: 9,
    mintAuthority: "",
    freezeAuthority: "",
    name: "",
    symbol: "",
    uri: "",
    createMetadata: true,
  })

  const [mintTokenForm, setMintTokenForm] = useState({
    destination: "",
    amount: "",
  })

  const [loading, setLoading] = useState({
    initMint: false,
    mintToken: false,
  })

  const [successTx, setSuccessTx] = useState({
    initMint: "",
    mintToken: "",
    metadata: "",
  })

  const [errors, setErrors] = useState({
    initMint: "",
    mintToken: "",
    metadata: "",
  })

  // State to store the created mint's public key for later use
  const [mintPubKey, setMintPubKey] = useState<PublicKey | null>(null)
  const [airdropLoading, setAirdropLoading] = useState(false)
  const [walletBalance, setWalletBalance] = useState<number | null>(null)
  const [idl, setIdl] = useState<any>(null)
  
  // Program verification state
  const [programStatus, setProgramStatus] = useState<{
    deployed: boolean
    hasIdl: boolean
    executable: boolean
    owner: string | null
    checking: boolean
  }>({
    deployed: false,
    hasIdl: false,
    executable: false,
    owner: null,
    checking: false
  })


  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text)
    toast({
      title: "Copied!",
      description: "Address copied to clipboard",
    })
  }

  const requestAirdrop = async () => {
    if (!publicKey) {
      toast({
        title: "Connect wallet first",
        description: "Please connect your wallet to request an airdrop",
        variant: "destructive",
      })
      return
    }

    setAirdropLoading(true)
    try {
      const signature = await connection.requestAirdrop(
        publicKey,
        2 * anchor.web3.LAMPORTS_PER_SOL // 2 SOL
      )
      
      const latestBlockhash = await connection.getLatestBlockhash()
      await connection.confirmTransaction({
        signature,
        blockhash: latestBlockhash.blockhash,
        lastValidBlockHeight: latestBlockhash.lastValidBlockHeight
      }, 'confirmed')
      
      const balance = await connection.getBalance(publicKey)
      toast({
        title: "Airdrop successful!",
        description: `Your balance is now ${(balance / anchor.web3.LAMPORTS_PER_SOL).toFixed(2)} SOL`,
      })
    } catch (error) {
      console.error('Airdrop failed:', error)
      toast({
        title: "Airdrop failed",
        description: "Please try again in a few seconds. You might have requested too many airdrops.",
        variant: "destructive",
      })
    } finally {
      setAirdropLoading(false)
    }
  }

  const createMetadataAccount = async (
    connection: anchor.web3.Connection,
    mintKey: PublicKey,
    mintAuthorityKey: PublicKey,
    payerKey: PublicKey,
    name: string,
    symbol: string,
    uri: string
  ) => {
    try {
      // Derive the metadata account PDA
      const [metadataAccount] = PublicKey.findProgramAddressSync(
        [Buffer.from("metadata"), METADATA_PROGRAM_ID.toBuffer(), mintKey.toBuffer()],
        METADATA_PROGRAM_ID
      )
      
      // Create the metadata instruction
      const metadataInstruction = createCreateMetadataAccountV3Instruction(
        {
          metadata: metadataAccount,
          mint: mintKey,
          mintAuthority: mintAuthorityKey,
          payer: payerKey,
          updateAuthority: mintAuthorityKey,
        },
        {
          createMetadataAccountArgsV3: {
            data: {
              name,
              symbol,
              uri,
              sellerFeeBasisPoints: 0,
              creators: null,
              collection: null,
              uses: null,
            },
            isMutable: true,
            collectionDetails: null,
          },
        }
      )

      // Create and send the transaction
      const transaction = new Transaction().add(metadataInstruction)
      transaction.feePayer = payerKey
      const { blockhash } = await connection.getLatestBlockhash()
      transaction.recentBlockhash = blockhash

      if (!signTransaction) throw new Error("Wallet does not support signing")
      const signedTx = await signTransaction(transaction)
      const txId = await connection.sendRawTransaction(signedTx.serialize())
      const latestBlockhash = await connection.getLatestBlockhash()
      await connection.confirmTransaction({
        signature: txId,
        blockhash: latestBlockhash.blockhash,
        lastValidBlockHeight: latestBlockhash.lastValidBlockHeight
      }, 'confirmed')
      
      return { txId, metadataAccount }
    } catch (error) {
      console.error("Error creating metadata account:", error)
      throw error
    }
  }

  const handleInitializeMint = async () => {
    console.log("=== INIT MINT DEBUG START ===");
    console.log("1. Wallet connected:", connected);
    console.log("2. Public key:", publicKey?.toString());
    console.log("3. Parent wallet:", parentWallet);
    console.log("4. Wallet ready:", walletReady);
    console.log("5. Wallet pubkey:", walletPubKey);
    console.log("6. Program ID:", programId);
    console.log("7. Is in iframe:", window.parent !== window);
    console.log("8. signTransaction available:", !!signTransaction);
    console.log("9. Program status:", programStatus);
    
    setLoading((prev) => ({ ...prev, initMint: true }))
    setErrors((prev) => ({ ...prev, initMint: "", metadata: "" }))
    setSuccessTx((prev) => ({ ...prev, metadata: "" }))

    try {
      // Check if we have wallet connection (either direct or through parent)
      if (!walletReady) {
        console.error("WALLET NOT READY - connected:", connected, "parentWallet:", parentWallet);
        
        // If in iframe and no wallet, request connection from parent
        if (window.parent !== window && !parentWallet.connected) {
          console.log("Requesting wallet connection from parent...");
          window.parent.postMessage({ type: "wallet_connect_request" }, "*");
          throw new Error("Please connect your wallet in the main window");
        }
        throw new Error("Wallet not connected");
      }
      
      // Use parent wallet public key if in iframe and not directly connected
      const activePublicKey = publicKey || (parentWallet.publicKey ? new PublicKey(parentWallet.publicKey) : null);
      console.log("Active public key:", activePublicKey?.toString());
      
      if (!activePublicKey) {
        console.error("NO PUBLIC KEY AVAILABLE");
        console.log("publicKey:", publicKey);
        console.log("parentWallet.publicKey:", parentWallet.publicKey);
        throw new Error("No wallet public key available");
      }
      
      if (!programId || programId === "") {
        console.error("PROGRAM ID MISSING:", programId);
        console.log("INITIAL_PROGRAM_ID:", INITIAL_PROGRAM_ID);
        toast({
          title: "Program ID missing",
          description: "Cannot initialize mint without a program. Please deploy first.",
          variant: "destructive",
        })
        throw new Error("Program ID is missing - please deploy the program first");
      }
      // ─────── RUNTIME ENV CHECK ───────
      console.log("[DEBUG] Program ID from .env =", programId)

      const programIdKey = new PublicKey(programId)
      console.log("Program ID key created:", programIdKey.toBase58())
      
      // Check if program exists on chain
      console.log("Checking if program exists on chain...");
      const programAccount = await connection.getAccountInfo(programIdKey);
      if (!programAccount) {
        console.error("PROGRAM NOT FOUND ON CHAIN");
        throw new Error("Program not deployed. Please deploy the program first.");
      }
      console.log("Program found on chain, executable:", programAccount.executable);
      
      // Check wallet balance
      const balance = await connection.getBalance(activePublicKey);
      console.log("Wallet balance:", balance / anchor.web3.LAMPORTS_PER_SOL, "SOL");
      if (balance < 0.01 * anchor.web3.LAMPORTS_PER_SOL) {
        console.error("INSUFFICIENT BALANCE");
        throw new Error("Insufficient SOL balance. Click 'Get Devnet SOL' first.");
      }
      
      // Set up Anchor provider and program
      console.log("Setting up Anchor provider...");
      
      // Check if we're in iframe and need special handling
      const isInIframe = window.parent !== window;
      console.log("Is in iframe:", isInIframe);
      console.log("Connected directly:", connected);
      console.log("Parent wallet connected:", parentWallet.connected);
      
      let anchorWallet;
      if (isInIframe && !connected && parentWallet.connected) {
        console.log("Using iframe wallet adapter for parent wallet");
        // We're in iframe and using parent wallet
        // The IframeWalletAdapter should handle this
        anchorWallet = {
          publicKey: activePublicKey!,
          signTransaction: async (_tx: Transaction) => {
            console.log("Iframe: Sending transaction to parent for signing");
            throw new Error("Iframe signing not yet implemented - please connect wallet directly");
          },
          signAllTransactions: async (_txs: Transaction[]) => {
            throw new Error("Iframe signing not yet implemented");
          }
        };
      } else if (connected && signTransaction) {
        console.log("Using direct wallet connection");
        anchorWallet = {
          publicKey: publicKey!,
          signTransaction: signTransaction!,
          signAllTransactions: signAllTransactions!,
        }
      } else {
        console.error("No valid wallet configuration found");
        console.log("connected:", connected);
        console.log("signTransaction:", !!signTransaction);
        console.log("parentWallet:", parentWallet);
        throw new Error("Wallet not properly connected");
      }
      
      const provider = new anchor.AnchorProvider(connection, anchorWallet as anchor.Wallet, anchor.AnchorProvider.defaultOptions())
      anchor.setProvider(provider)
      console.log("Provider set up successfully");
      
      const program = await getProgram(provider, programIdKey)
      console.log("[DEBUG] program.programId =", program.programId.toBase58())
      // Determine mint authority (use wallet if none provided)
      // ─────── MINT AUTHORITY VALIDATION ───────
      let mintAuthorityPubkey: PublicKey
      try {
        mintAuthorityPubkey = initMintForm.mintAuthority
          ? new PublicKey(initMintForm.mintAuthority)
          : publicKey!
        console.log("[DEBUG] mintAuthorityPubkey =", mintAuthorityPubkey.toBase58())
      } catch (err) {
        console.error("[ERROR] Invalid mintAuthority provided:", initMintForm.mintAuthority, err)
        setErrors((prev) => ({ ...prev, initMint: "Invalid Mint Authority address." }))
        toast({
          title: "Invalid address",
          description: "Mint authority address is not a valid public key.",
          variant: "destructive",
        })
        return
      }
      // Warn if freeze authority is provided (not supported by program)
      if (initMintForm.freezeAuthority.trim()) {
        toast({
          title: "Note",
          description: "Freeze authority is not supported and will be set to none.",
        })
      }
      // Generate a new Keypair for the token mint account
      const mintAccount = Keypair.generate()
      dbg("Generated mint Keypair", mintAccount.publicKey.toBase58())
              // Decimals handling as plain number
        const decimals = initMintForm.decimals | 0  // force integer
        console.log("[DEBUG] decimals (raw) =", initMintForm.decimals)
        console.log("[DEBUG] decimals (integer) =", decimals)

      console.log("[DEBUG] Accounts passed to initializeMint", {
        payer: publicKey!.toBase58(),
        tokenMint: mintAccount.publicKey.toBase58(),
        systemProgram: anchor.web3.SystemProgram.programId.toBase58(),
        tokenProgram: TOKEN_PROGRAM_ID.toBase58(),
        rent: anchor.web3.SYSVAR_RENT_PUBKEY.toBase58(),
      })

      dbg("Calling initializeMint()", { decimals, mintAuthority: mintAuthorityPubkey.toBase58() })
      const txSig = await program.methods
        .initializeMint(decimals, mintAuthorityPubkey)
        .accounts({
          payer: publicKey!,
          tokenMint: mintAccount.publicKey,
          systemProgram: anchor.web3.SystemProgram.programId,
          tokenProgram: TOKEN_PROGRAM_ID,
          rent: anchor.web3.SYSVAR_RENT_PUBKEY,
        })
        .signers([mintAccount])
        .rpc()
      
      // Save mint public key for use in mintToken step
      setMintPubKey(mintAccount.publicKey)
      dbg("initializeMint ➜ txSig", txSig)
      setSuccessTx((prev) => ({ ...prev, initMint: txSig }))
      toast({
        title: "Mint Initialized!",
        description: "Your token mint has been successfully created.",
      })

      // Create metadata if requested and fields are provided
      if (
        initMintForm.createMetadata && 
        initMintForm.name.trim() && 
        initMintForm.symbol.trim() && 
        initMintForm.uri.trim()
      ) {
        try {
          const { txId } = await createMetadataAccount(
            connection,
            mintAccount.publicKey,
            mintAuthorityPubkey,
            publicKey!,
            initMintForm.name.trim(),
            initMintForm.symbol.trim(),
            initMintForm.uri.trim()
          )
          
          setSuccessTx((prev) => ({ ...prev, metadata: txId }))
          toast({
            title: "Metadata Created!",
            description: "Token metadata has been successfully created.",
          })
        } catch (error) {
          console.error("Metadata creation error:", error)
          setErrors((prev) => ({ 
            ...prev, 
            metadata: "Failed to create metadata. Mint was created successfully, but metadata creation failed." 
          }))
          toast({
            title: "Metadata Error",
            description: "Failed to create token metadata",
            variant: "destructive",
          })
        }
      }
    } catch (error) {
      dbg("InitializeMint ‼️ error", error)
      setErrors((prev) => ({ ...prev, initMint: "Failed to initialize mint. Please try again." }))
      toast({
        title: "Error",
        description: "Failed to initialize mint",
        variant: "destructive",
      })
    } finally {
      setLoading((prev) => ({ ...prev, initMint: false }))
      dbg("handleInitializeMint() finished")
    }
  }

  const handleMintToken = async () => {
    setLoading((prev) => ({ ...prev, mintToken: true }))
    setErrors((prev) => ({ ...prev, mintToken: "" }))

    try {
      if (!publicKey || !connected) {
        dbg("MintToken abort – wallet not connected")
        throw new Error("Wallet not connected")
      }
      if (!mintPubKey) throw new Error("Mint not initialized")
      if (!programId) {
        toast({
          title: "Program ID missing",
          description: "Cannot mint tokens without a program.",
          variant: "destructive",
        })
        return
      }
      // Set up Anchor provider and program (reuse connection and wallet)
      const anchorWallet = {
        publicKey: publicKey,
        signTransaction: signTransaction!,
        signAllTransactions: signAllTransactions!,
      }
      const provider = new anchor.AnchorProvider(connection, anchorWallet as anchor.Wallet, anchor.AnchorProvider.defaultOptions())
      anchor.setProvider(provider)
      const programIdKey = new PublicKey(programId)

      const program = await getProgram(provider, programIdKey)
      // Mint authority must match the one set during initialization
      const mintAuthorityPubkey = initMintForm.mintAuthority
        ? new PublicKey(initMintForm.mintAuthority)
        : publicKey
      if (!publicKey.equals(mintAuthorityPubkey)) {
        throw new Error("Current wallet is not the mint authority")
      }
      // Parse destination address and get/create associated token account
      const destinationPubkey = new PublicKey(mintTokenForm.destination)
      const ata = await getAssociatedTokenAddress(mintPubKey, destinationPubkey)
      const ataInfo = await connection.getAccountInfo(ata)
      const preIx: anchor.web3.TransactionInstruction[] = []
      if (!ataInfo) {
        preIx.push(
          createAssociatedTokenAccountInstruction(publicKey, ata, destinationPubkey, mintPubKey)
        )
      }
              // Call mint_to instruction on the Anchor program using fluent methods API
        if (!/^\d+$/.test(mintTokenForm.amount)) {
          throw new Error("Amount must be a positive integer")
        }
        const amountBN = new BN(mintTokenForm.amount)
      dbg("Calling mintTo()", { amount: mintTokenForm.amount })
      const txSig = await program.methods
        .mintTo(amountBN)
        .accounts({
          mintAuthority: publicKey,
          tokenMint: mintPubKey,
          destinationTokenAccount: ata,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .preInstructions(preIx)
        .rpc()
      
      dbg("mintTo ➜ txSig", txSig)
      setSuccessTx((prev) => ({ ...prev, mintToken: txSig }))
      toast({
        title: "Tokens Minted!",
        description: `Successfully minted ${mintTokenForm.amount} tokens.`,
      })
    } catch (error) {
      dbg("MintToken ‼️ error", error)
      setErrors((prev) => ({
        ...prev,
        mintToken: (error as Error).message.includes("Mint not initialized")
          ? "Please initialize a mint first."
          : "Failed to mint tokens. Please try again.",
      }))
      toast({
        title: "Error",
        description: "Failed to mint tokens",
        variant: "destructive",
      })
    } finally {
      setLoading((prev) => ({ ...prev, mintToken: false }))
      dbg("handleMintToken() finished")
    }
  }

  return (
    <TooltipProvider>
      <div className="min-h-screen overflow-y-auto bg-gradient-to-br from-white via-blue-50/30 to-purple-50/30">
        {/* Optional whimsical blob background */}
        <div className="fixed top-0 right-0 w-96 h-96 bg-gradient-to-br from-blue-200/10 to-purple-200/10 rounded-full blur-3xl -z-10" />
        
        {/* Debug Panel */}
        <DebugPanel
          programId={programId}
          programStatus={programStatus}
          walletPubKey={walletPubKey}
          mintPubKey={mintPubKey}
          connection={connection}
        />

        <div className="container mx-auto px-4 py-8 max-w-4xl">
          {/* Header */}
          <div className="flex items-center justify-between mb-8">
            <div className="flex items-center gap-4">
              <h1 className="text-4xl font-semibold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                SolMint
              </h1>
              <div className="flex items-center gap-2 text-sm text-gray-600">
                <span>Program ID:</span>
                <Badge
                  variant="outline"
                  className="font-mono cursor-pointer hover:bg-gray-50 transition-colors"
                  onClick={() => copyToClipboard(programId)}
                >
                  {shortenAddress(programId)}
                  <Copy className="w-3 h-3 ml-1" />
                </Badge>
                {programStatus.checking ? (
                  <Badge variant="secondary" className="gap-1">
                    <Loader2 className="w-3 h-3 animate-spin" />
                    Checking...
                  </Badge>
                ) : programStatus.deployed ? (
                  <Badge variant={programStatus.executable ? "default" : "destructive"} className="gap-1">
                    {programStatus.executable ? "✓ Deployed" : "Not Executable"}
                  </Badge>
                ) : (
                  <Badge variant="destructive" className="gap-1">
                    Not Deployed
                  </Badge>
                )}
              </div>
            </div>

            <div className="flex items-center gap-4">
              <Button
                variant="outline"
                size="icon"
                onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
                className="rounded-full"
              >
                <Sun className="h-4 w-4 rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
                <Moon className="absolute h-4 w-4 rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
              </Button>

              {/* always render the genuine WalletMultiButton so the click
                  counts as a real user-gesture inside the iframe */}
              <div className="wallet-adapter-button-container">
                <WalletMultiButton className="!bg-gradient-to-r !from-blue-500 !to-purple-500 hover:!from-blue-600 hover:!to-purple-600 !rounded-full !px-6 !py-2 !text-white !font-medium !transition-all !duration-300 hover:!scale-105 !shadow-lg" />
              </div>

              {walletReady && walletPubKey && (
                <>
                  <Badge variant="secondary" className="font-mono">
                    {shortenAddress(walletPubKey)}
                  </Badge>
                  <Button
                    onClick={requestAirdrop}
                    disabled={airdropLoading}
                    variant="outline"
                    size="sm"
                    className="rounded-full"
                  >
                    {airdropLoading ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        Requesting...
                      </>
                    ) : (
                      "Get Devnet SOL"
                    )}
                  </Button>
                </>
              )}
            </div>
          </div>

          {!walletReady && (
            <Alert className="mb-8 border-blue-200 bg-blue-50/50">
              <Info className="h-4 w-4" />
              <AlertDescription>Please connect your wallet to start minting tokens.</AlertDescription>
            </Alert>
          )}

          {/* Diagnostic Panel - Shows debugging information */}
          <Card className="mb-8 backdrop-blur-sm bg-yellow-50/80 border-yellow-200 shadow-lg rounded-3xl">
            <CardHeader className="pb-4">
              <CardTitle className="text-lg font-semibold text-yellow-800 flex items-center gap-2">
                <Info className="w-5 h-5" />
                Debug Information
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3 text-sm font-mono">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <span className="text-gray-600">Environment:</span>
                  <Badge variant="outline" className="ml-2">
                    {typeof window !== 'undefined' && window.self !== window.top ? 'Iframe' : 'Direct'}
                  </Badge>
                </div>
                <div>
                  <span className="text-gray-600">Wallet Connected:</span>
                  <Badge variant={connected ? "default" : "destructive"} className="ml-2">
                    {connected ? 'Yes' : 'No'}
                  </Badge>
                </div>
                <div>
                  <span className="text-gray-600">Public Key:</span>
                  <Badge variant="outline" className="ml-2 font-mono text-xs">
                    {publicKey ? shortenAddress(publicKey.toString()) : 'None'}
                  </Badge>
                </div>
                <div>
                  <span className="text-gray-600">Parent Wallet:</span>
                  <Badge variant={parentWallet ? "default" : "secondary"} className="ml-2">
                    {parentWallet ? 'Connected' : 'Not Connected'}
                  </Badge>
                </div>
                <div>
                  <span className="text-gray-600">Program ID:</span>
                  <Badge variant={programId ? "default" : "destructive"} className="ml-2 font-mono text-xs">
                    {programId ? shortenAddress(programId) : 'Missing'}
                  </Badge>
                </div>
                <div>
                  <span className="text-gray-600">Program Status:</span>
                  <Badge 
                    variant={programStatus.deployed && programStatus.executable ? "default" : "destructive"} 
                    className="ml-2"
                  >
                    {programStatus.checking ? 'Checking...' : 
                     programStatus.deployed ? (programStatus.executable ? 'Deployed' : 'Not Executable') : 'Not Found'}
                  </Badge>
                </div>
                <div>
                  <span className="text-gray-600">RPC Endpoint:</span>
                  <Badge variant="outline" className="ml-2 text-xs">
                    {connection.rpcEndpoint.includes('devnet') ? 'Devnet' : 'Custom'}
                  </Badge>
                </div>
                <div>
                  <span className="text-gray-600">Balance:</span>
                  <Badge variant="outline" className="ml-2">
                    {walletBalance !== null ? `${walletBalance.toFixed(4)} SOL` : 'Unknown'}
                  </Badge>
                </div>
              </div>
              
              <div className="mt-4 pt-4 border-t border-yellow-200 space-y-2">
                <Button
                  onClick={async () => {
                    console.log("=== DIAGNOSTIC CHECK ===");
                    console.log("1. Window context:", {
                      isIframe: window.self !== window.top,
                      location: window.location.href,
                      parentOrigin: window.parent.location.origin
                    });
                    console.log("2. Wallet state:", {
                      connected,
                      publicKey: publicKey?.toString(),
                      parentWallet,
                      walletReady
                    });
                    console.log("3. Program info:", {
                      programId,
                      programStatus,
                      idl: !!idl
                    });
                    console.log("4. Connection:", {
                      endpoint: connection.rpcEndpoint,
                      commitment: connection.commitment
                    });
                    
                    // Test message passing
                    if (window.self !== window.top) {
                      console.log("5. Testing parent communication...");
                      window.parent.postMessage({ type: "wallet_state_request" }, "*");
                    }
                    
                    // Check program on chain
                    if (programId) {
                      try {
                        const programPubkey = new PublicKey(programId);
                        const info = await connection.getAccountInfo(programPubkey);
                        console.log("6. Program account info:", {
                          exists: !!info,
                          executable: info?.executable,
                          owner: info?.owner.toString(),
                          lamports: info?.lamports
                        });
                      } catch (e) {
                        console.error("6. Failed to fetch program info:", e);
                      }
                    }
                    
                    toast({
                      title: "Diagnostics",
                      description: "Check browser console for detailed output"
                    });
                  }}
                  variant="outline"
                  size="sm"
                  className="w-full"
                >
                  Run Full Diagnostics (Check Console)
                </Button>
                
                <Button
                  onClick={async () => {
                    console.log("=== TESTING DIRECT PHANTOM CONNECTION ===");
                    
                    // Check if we're in an iframe
                    const isIframe = window.self !== window.top;
                    console.log("Running in iframe:", isIframe);
                    
                    // Check for Phantom in window
                    if ((window as any).solana && (window as any).solana.isPhantom) {
                      console.log("Phantom detected in window!");
                      try {
                        const resp = await (window as any).solana.connect();
                        console.log("✅ Connected to Phantom directly:", resp.publicKey.toString());
                        toast({
                          title: "Success!",
                          description: `Connected to Phantom: ${resp.publicKey.toString().slice(0, 8)}...`,
                        });
                      } catch (err) {
                        console.error("❌ Failed to connect to Phantom:", err);
                        toast({
                          title: "Connection Failed",
                          description: "Failed to connect to Phantom wallet",
                          variant: "destructive"
                        });
                      }
                    } else {
                      console.error("❌ Phantom wallet not found in window!");
                      console.log("Window.solana:", (window as any).solana);
                      
                      // If in iframe, try to request parent connection
                      if (isIframe) {
                        console.log("Requesting parent window to connect wallet...");
                        window.parent.postMessage({ type: "wallet_connect_request" }, "*");
                        toast({
                          title: "Iframe Mode",
                          description: "Requesting parent window to connect wallet",
                        });
                      } else {
                        toast({
                          title: "Phantom Not Found",
                          description: "Please install Phantom wallet extension",
                          variant: "destructive"
                        });
                        window.open("https://phantom.app/", "_blank");
                      }
                    }
                  }}
                  variant="outline"
                  size="sm"
                  className="w-full"
                >
                  Test Direct Phantom Connection
                </Button>
              </div>
            </CardContent>
          </Card>

          <div className="grid gap-8 md:grid-cols-2">
            {/* Initialize Mint Card */}
            <Card className="backdrop-blur-sm bg-white/80 border-0 shadow-lg rounded-3xl transition-all duration-300 hover:shadow-xl hover:scale-[1.02]">
              <CardHeader className="pb-4">
                <CardTitle className="text-2xl font-semibold text-gray-800">Initialize Mint</CardTitle>
                <CardDescription className="text-gray-600">
                  Create a new SPL token mint with custom parameters
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="space-y-2">
                  <div className="flex items-center gap-2">
                    <Label htmlFor="decimals" className="text-sm font-medium">
                      Decimals
                    </Label>
                    <Tooltip>
                      <TooltipTrigger>
                        <Info className="w-4 h-4 text-gray-400" />
                      </TooltipTrigger>
                      <TooltipContent>
                        <p>Number of decimal places for your token (0-9)</p>
                      </TooltipContent>
                    </Tooltip>
                  </div>
                  <Input
                    id="decimals"
                    type="number"
                    min="0"
                    max="9"
                    value={initMintForm.decimals}
                    onChange={(e) =>
                      setInitMintForm((prev) => ({ ...prev, decimals: Number.parseInt(e.target.value) || 0 }))
                    }
                    className="rounded-xl border-blue-200 focus:border-blue-400 focus:ring-blue-400/20"
                    disabled={!walletReady}
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="mintAuthority" className="text-sm font-medium">
                    Mint Authority
                  </Label>
                  <Input
                    id="mintAuthority"
                    placeholder="Enter mint authority public key"
                    value={initMintForm.mintAuthority}
                    onChange={(e) => setInitMintForm((prev) => ({ ...prev, mintAuthority: e.target.value }))}
                    className="rounded-xl border-blue-200 focus:border-blue-400 focus:ring-blue-400/20 font-mono text-sm"
                    disabled={!walletReady}
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="freezeAuthority" className="text-sm font-medium">
                    Freeze Authority (Optional)
                  </Label>
                  <Input
                    id="freezeAuthority"
                    placeholder="Enter freeze authority public key"
                    value={initMintForm.freezeAuthority}
                    onChange={(e) => setInitMintForm((prev) => ({ ...prev, freezeAuthority: e.target.value }))}
                    className="rounded-xl border-blue-200 focus:border-blue-400 focus:ring-blue-400/20 font-mono text-sm"
                    disabled={!walletReady}
                  />
                </div>

                {/* Metadata fields */}
                <div className="pt-4 border-t border-gray-100">
                  <div className="flex items-center gap-2 mb-4">
                    <Label htmlFor="createMetadata" className="text-sm font-medium cursor-pointer">
                      Create Token Metadata
                    </Label>
                    <input
                      id="createMetadata"
                      type="checkbox"
                      checked={initMintForm.createMetadata}
                      onChange={(e) => setInitMintForm((prev) => ({ ...prev, createMetadata: e.target.checked }))}
                      className="rounded border-blue-200 text-blue-500 focus:ring-blue-400/20"
                    />
                    <Tooltip>
                      <TooltipTrigger>
                        <Info className="w-4 h-4 text-gray-400" />
                      </TooltipTrigger>
                      <TooltipContent>
                        <p>Create on-chain metadata for your token (name, symbol, URI)</p>
                      </TooltipContent>
                    </Tooltip>
                  </div>

                  {initMintForm.createMetadata && (
                    <div className="space-y-4">
                      <div className="space-y-2">
                        <Label htmlFor="tokenName" className="text-sm font-medium">
                          Token Name
                        </Label>
                        <Input
                          id="tokenName"
                          placeholder="Enter token name"
                          value={initMintForm.name}
                          onChange={(e) => setInitMintForm((prev) => ({ ...prev, name: e.target.value }))}
                          className="rounded-xl border-blue-200 focus:border-blue-400 focus:ring-blue-400/20"
                          disabled={!walletReady}
                        />
                      </div>

                      <div className="space-y-2">
                        <Label htmlFor="tokenSymbol" className="text-sm font-medium">
                          Token Symbol
                        </Label>
                        <Input
                          id="tokenSymbol"
                          placeholder="Enter token symbol (max 10 chars)"
                          value={initMintForm.symbol}
                          onChange={(e) => setInitMintForm((prev) => ({ ...prev, symbol: e.target.value.toUpperCase().slice(0, 10) }))}
                          className="rounded-xl border-blue-200 focus:border-blue-400 focus:ring-blue-400/20"
                          disabled={!walletReady}
                        />
                      </div>

                      <div className="space-y-2">
                        <Label htmlFor="tokenUri" className="text-sm font-medium">
                          Token URI
                        </Label>
                        <Input
                          id="tokenUri"
                          placeholder="Enter metadata URI (JSON)"
                          value={initMintForm.uri}
                          onChange={(e) => setInitMintForm((prev) => ({ ...prev, uri: e.target.value }))}
                          className="rounded-xl border-blue-200 focus:border-blue-400 focus:ring-blue-400/20"
                          disabled={!walletReady}
                        />
                        <p className="text-xs text-gray-500">
                          URI should point to a JSON file following the{" "}
                          <a
                            href="https://docs.metaplex.com/programs/token-metadata/token-standard"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-blue-500 hover:underline"
                          >
                            Metaplex standard
                          </a>
                        </p>
                      </div>
                    </div>
                  )}
                </div>

                {errors.initMint && (
                  <Alert variant="destructive" className="rounded-xl">
                    <AlertDescription>{errors.initMint}</AlertDescription>
                  </Alert>
                )}

                {errors.metadata && (
                  <Alert variant="destructive" className="rounded-xl">
                    <AlertDescription>{errors.metadata}</AlertDescription>
                  </Alert>
                )}

                <Button
                  onClick={handleInitializeMint}
                  disabled={!walletReady || loading.initMint}
                  className="w-full bg-gradient-to-r from-blue-500 to-purple-500 hover:from-blue-600 hover:to-purple-600 text-white rounded-xl py-6 font-medium transition-all duration-300 hover:scale-105 shadow-lg"
                >
                  {loading.initMint ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      Initializing...
                    </>
                  ) : (
                    "Initialize Mint"
                  )}
                </Button>

                {successTx.initMint && (
                  <div className="flex items-center gap-2 p-3 bg-green-50 rounded-xl border border-green-200">
                    <Badge className="bg-gradient-to-r from-blue-500 to-purple-500 text-white">
                      <ExternalLink className="w-3 h-3 mr-1" />
                      View on Explorer
                    </Badge>
                    <span className="text-sm text-green-700 font-mono">{shortenAddress(successTx.initMint)}</span>
                  </div>
                )}

                {successTx.metadata && (
                  <div className="flex items-center gap-2 p-3 bg-green-50 rounded-xl border border-green-200">
                    <Badge className="bg-gradient-to-r from-blue-500 to-purple-500 text-white">
                      <ExternalLink className="w-3 h-3 mr-1" />
                      View Metadata TX
                    </Badge>
                    <span className="text-sm text-green-700 font-mono">{shortenAddress(successTx.metadata)}</span>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Mint New Token Card */}
            <Card className="backdrop-blur-sm bg-white/80 border-0 shadow-lg rounded-3xl transition-all duration-300 hover:shadow-xl hover:scale-[1.02]">
              <CardHeader className="pb-4">
                <CardTitle className="text-2xl font-semibold text-gray-800">Mint New Token</CardTitle>
                <CardDescription className="text-gray-600">Mint tokens to a destination address</CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="space-y-2">
                  <Label htmlFor="destination" className="text-sm font-medium">
                    Destination Address
                  </Label>
                  <Input
                    id="destination"
                    placeholder="Enter destination wallet address"
                    value={mintTokenForm.destination}
                    onChange={(e) => setMintTokenForm((prev) => ({ ...prev, destination: e.target.value }))}
                    className="rounded-xl border-blue-200 focus:border-blue-400 focus:ring-blue-400/20 font-mono text-sm"
                    disabled={!walletReady}
                  />
                </div>

                <div className="space-y-2">
                  <div className="flex items-center gap-2">
                    <Label htmlFor="amount" className="text-sm font-medium">
                      Amount
                    </Label>
                    <Tooltip>
                      <TooltipTrigger>
                        <Info className="w-4 h-4 text-gray-400" />
                      </TooltipTrigger>
                      <TooltipContent>
                        <p>Number of tokens to mint (u64 format)</p>
                      </TooltipContent>
                    </Tooltip>
                  </div>
                  <Input
                    id="amount"
                    type="number"
                    placeholder="Enter amount to mint"
                    value={mintTokenForm.amount}
                    onChange={(e) => setMintTokenForm((prev) => ({ ...prev, amount: e.target.value }))}
                    className="rounded-xl border-blue-200 focus:border-blue-400 focus:ring-blue-400/20"
                    disabled={!walletReady}
                  />
                </div>

                {errors.mintToken && (
                  <Alert variant="destructive" className="rounded-xl">
                    <AlertDescription>{errors.mintToken}</AlertDescription>
                  </Alert>
                )}

                <Button
                  onClick={handleMintToken}
                  disabled={!walletReady || loading.mintToken || !mintTokenForm.destination || !mintTokenForm.amount}
                  className="w-full bg-gradient-to-r from-blue-500 to-purple-500 hover:from-blue-600 hover:to-purple-600 text-white rounded-xl py-6 font-medium transition-all duration-300 hover:scale-105 shadow-lg"
                >
                  {loading.mintToken ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      Minting...
                    </>
                  ) : (
                    "Mint Token"
                  )}
                </Button>

                {successTx.mintToken && (
                  <div className="flex items-center gap-2 p-3 bg-green-50 rounded-xl border border-green-200">
                    <Badge className="bg-gradient-to-r from-blue-500 to-purple-500 text-white">
                      <ExternalLink className="w-3 h-3 mr-1" />
                      View on Explorer
                    </Badge>
                    <span className="text-sm text-green-700 font-mono">{shortenAddress(successTx.mintToken)}</span>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </TooltipProvider>
  )
}